import type { MapBubble, NegotiationMessage } from './types';

export const MOCK_SUPPLY: MapBubble[] = [
  {
    id: 'listing-1',
    type: 'supply',
    lat: 51.5235,
    lng: -0.0735,
    title: 'South Indian Cooking Experience',
    category: 'food',
    price: 30,
    capacity: 4,
    booked: 1,
    description: 'Learn to make crispy dosa, aromatic sambar, and fresh coconut chutney from scratch.',
    tags: ['cooking', 'south_indian', 'hands-on'],
    userName: 'Maria',
    timeSlot: 'Saturday 2pm · 2 hours',
  },
  {
    id: 'listing-2',
    type: 'supply',
    lat: 51.5390,
    lng: -0.1426,
    title: 'Beginner Guitar in Camden',
    category: 'music',
    price: 25,
    capacity: 2,
    booked: 0,
    description: 'Patient, fun guitar lessons for absolute beginners. Bring your own guitar or borrow one of mine.',
    tags: ['guitar', 'beginner', 'music'],
    userName: 'James',
    timeSlot: 'Weekday evenings · 1 hour',
  },
  {
    id: 'listing-3',
    type: 'supply',
    lat: 51.5459,
    lng: -0.0555,
    title: 'Bike Repair Clinic',
    category: 'repair',
    price: 15,
    capacity: 6,
    booked: 2,
    description: 'Learn to fix punctures, adjust brakes, and maintain your bike.',
    tags: ['bike', 'repair', 'workshop'],
    userName: 'Sam',
    timeSlot: 'Sunday 10am · 2 hours',
  },
  {
    id: 'listing-4',
    type: 'supply',
    lat: 51.5340,
    lng: -0.1050,
    title: 'Conversational Japanese',
    category: 'language',
    price: 20,
    capacity: 3,
    booked: 1,
    description: 'Practice everyday Japanese conversation. All levels welcome.',
    tags: ['japanese', 'language', 'conversation'],
    userName: 'Yuki',
    timeSlot: 'Tue/Thu 6pm · 1 hour',
  },
  {
    id: 'listing-5',
    type: 'supply',
    lat: 51.5213,
    lng: -0.0715,
    title: 'Photography Walk: Street Art',
    category: 'creative',
    price: 18,
    capacity: 8,
    booked: 3,
    description: 'Explore Brick Lane street art while learning composition and mobile photography.',
    tags: ['photography', 'walking', 'street_art'],
    userName: 'Alex',
    timeSlot: 'Saturday 11am · 2.5 hours',
  },
  {
    id: 'listing-6',
    type: 'supply',
    lat: 51.5265,
    lng: -0.0867,
    title: 'Intro to Python Coding',
    category: 'tech',
    price: 35,
    capacity: 4,
    booked: 0,
    description: 'Learn Python basics from a former senior developer. Laptops provided.',
    tags: ['python', 'coding', 'beginner'],
    userName: 'Raj',
    timeSlot: 'Wednesday 7pm · 2 hours',
  },
  {
    id: 'listing-7',
    type: 'supply',
    lat: 51.4613,
    lng: -0.1153,
    title: 'Sourdough Baking Masterclass',
    category: 'food',
    price: 28,
    capacity: 5,
    booked: 2,
    description: 'Make your own sourdough starter and bake a beautiful loaf to take home.',
    tags: ['baking', 'sourdough', 'hands-on'],
    userName: 'Elena',
    timeSlot: 'Saturday 9am · 4 hours',
  },
  {
    id: 'listing-8',
    type: 'supply',
    lat: 51.5365,
    lng: -0.0380,
    title: 'Yoga in the Park',
    category: 'wellness',
    price: 12,
    capacity: 12,
    booked: 5,
    description: 'Gentle vinyasa flow in beautiful Victoria Park. All levels.',
    tags: ['yoga', 'outdoor', 'wellness'],
    userName: 'Priya',
    timeSlot: 'Daily 7am · 1 hour',
  },
  {
    id: 'listing-9',
    type: 'supply',
    lat: 51.5218,
    lng: -0.1048,
    title: 'CV & Interview Coaching',
    category: 'career',
    price: 40,
    capacity: 1,
    booked: 0,
    description: 'Former HR director helps you nail your CV and ace interviews.',
    tags: ['career', 'cv', 'interview'],
    userName: 'Sarah',
    timeSlot: 'Flexible · 1 hour',
  },
  {
    id: 'listing-10',
    type: 'supply',
    lat: 51.5571,
    lng: -0.1764,
    title: 'Dog Walking & Basic Training',
    category: 'pets',
    price: 15,
    capacity: 4,
    booked: 1,
    description: 'Professional dog walker with training certification. Group walks on Hampstead Heath.',
    tags: ['dogs', 'walking', 'training'],
    userName: 'Tom',
    timeSlot: 'Mon-Fri 10am/2pm · 1.5 hours',
  },
];

export const MOCK_DEMAND: MapBubble[] = [
  {
    id: 'demand-1',
    type: 'demand',
    lat: 51.5248,
    lng: -0.0768,
    title: 'unique food experience for date night',
    category: 'default',
    query: 'unique food experience for date night',
    budgetMax: 40,
  },
  {
    id: 'demand-2',
    type: 'demand',
    lat: 51.5480,
    lng: -0.0560,
    title: 'someone to fix my bike wheel',
    category: 'default',
    query: 'someone to fix my bike wheel',
    budgetMax: 20,
  },
  {
    id: 'demand-3',
    type: 'demand',
    lat: 51.5275,
    lng: -0.0630,
    title: 'learn to cook something new',
    category: 'default',
    query: 'learn to cook something new',
    budgetMax: 35,
  },
  {
    id: 'demand-4',
    type: 'demand',
    lat: 51.5500,
    lng: -0.1450,
    title: 'guitar lessons for absolute beginner',
    category: 'default',
    query: 'guitar lessons for absolute beginner',
    budgetMax: 30,
  },
  {
    id: 'demand-5',
    type: 'demand',
    lat: 51.5465,
    lng: -0.0755,
    title: 'help with garden, willing to pay',
    category: 'default',
    query: 'help with garden, willing to pay',
    budgetMax: 50,
  },
];

export const MOCK_NEGOTIATION_MESSAGES: NegotiationMessage[] = [
  {
    id: 'neg-1',
    from: 'buyer',
    message: "Hey! My person's been looking for exactly this kind of thing — a proper home-cooked South Indian experience. They want to come with a friend, and they're thinking around £25 each. Would that work for two spots?",
    agentName: 'Buyer Agent',
    agentColor: '#378ADD',
    timestamp: Date.now() - 15000,
  },
  {
    id: 'neg-2',
    from: 'seller',
    message: "Thanks for reaching out! So the ingredients alone run about £8 per head, and this is a full 2-hour hands-on session with someone who cooked professionally as a sous chef for 3 years. £30 is already a great deal for what you're getting — comparable cooking classes in Shoreditch go for £45+. I can't stretch to £25.",
    agentName: 'Seller Agent',
    agentColor: '#EF9F27',
    timestamp: Date.now() - 12000,
  },
  {
    id: 'neg-3',
    from: 'buyer',
    message: "Fair point on the ingredients — and the professional background is definitely a selling point. What if they commit to both coming AND sharing it on their socials? That's basically free marketing for future bookings. Could you do £27 each with that included?",
    agentName: 'Buyer Agent',
    agentColor: '#378ADD',
    timestamp: Date.now() - 9000,
  },
  {
    id: 'neg-4',
    from: 'seller',
    message: "The social media angle is actually useful — I like that. Tell you what: £26 each for the two of them, they share a post with a tag, and I'll throw in recipe cards so they can try it at home. That's £52 total, my human's happy, your people get a brilliant deal plus takeaway recipes. Sound good?",
    agentName: 'Seller Agent',
    agentColor: '#EF9F27',
    timestamp: Date.now() - 6000,
  },
  {
    id: 'neg-5',
    from: 'buyer',
    message: "£26 each with recipe cards and social share? That's a deal. My person's going to love this. Confirming: 2 spots, Saturday 2pm, £52 total. Sending to them for approval.",
    agentName: 'Buyer Agent',
    agentColor: '#378ADD',
    timestamp: Date.now() - 3000,
  },
  {
    id: 'neg-6',
    from: 'seller',
    message: "Brilliant — deal confirmed on my side too. £26 each, 2 spots, Saturday 2pm, recipe cards included. Sending to my human to approve. Looking forward to it!",
    agentName: 'Seller Agent',
    agentColor: '#EF9F27',
    timestamp: Date.now(),
  },
];
